In [4]:
import numpy as np

In [10]:
dice = [i for i in range(1,7)]
diceResult = np.random.choice(dice, 100)
dice_result = np.random.randint(1, 7, 100) #강사님 답안
mean = diceResult.mean()
print(mean)

3.89


In [15]:
#array 더하기

array1 = np.array([[1,2,3],
           [4,5,6]])
array2 = np.array([[7,8,9],
           [10,11,12]])

array1+array2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
intArray = np.array( [_ for _ in range(1,10)])
intArray*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [28]:
zeroArray = np.zeros(10)
zeroArray[4] = 1
print(zeroArray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [35]:
arrayRange=np.arange(50)

#슬라이싱 해보라고 주신 문제
arrayRange[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [38]:
np.arange(1,10,5)

array([1, 6])

In [59]:
array4 = np.array([[['','','']]*3]*3, dtype='<U10')
array4

# np.zeros((3, 3, 3), dtype = "U10")

# a = np.array(['' for _ in range(27)], dtype='<U10')
# a.reshape(3, 3, 3)

# 동일한 결과

np.full((3,3,3), '', dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [61]:
np.full((3,3,3,), 'playdata', dtype='<U8') #=U8 해도 됨

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [65]:
#1부터 40까지 짝수를 갖는 1차원 ndarray 만들기
#그 shape을 변경해서 (2, 2, 5)로 변경하기

array5 = np.arange(2,41,2)
array5.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [68]:
#단위 행렬 만들기
# 1 0 0 0
# 0 1 0 0
# 0 0 1 0
# 0 0 0 1

np.eye(4)

#기본 float
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
array5.astype(int)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [81]:
np.random.seed(0)
array6 = np.random.randint(0,2,9)
array6.astype(bool).reshape(3,3)

array7 = np.random.randint(0,2,size=9)
array7.astype("?").reshape(3,3) # 이런 방법도 있음!! bool 확인

array([[ True,  True, False],
       [False,  True, False],
       [False, False, False]])

In [94]:
np.random.seed(0)  # 시드가 같으면 랜덤한 숫자를 만드는 규칙이 있어서
                   # 결과가 같게 나옴
array8 = np.random.rand(10)
(array8*10).astype(int)    # .astype('int') 이렇게 해도 됨

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3])

In [105]:
#np.ones((10,10))만들고 안쪽을 0으로 변경하는 거 도전
#인덱싱 
array9 = np.ones((10,10))
for i in range(1,9):
    for j in range(1,9):
        array9[i][j] = 0
        
print(array9,'\n')

#슬라이싱과 벡터화 연산 활용
array10 = np.ones((10,10))
array10[1:9, 1:9]=0
        
print(array10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [124]:
#슬라이싱과 벡터화 연산 활용
array11 = np.ones((10,10))
array11[:,0]=0
array11[:,-1]=0 #array[:, [0,-1]] = 0
array11[0]=0
array11[-1]=0  #array[[0,-1], :] = 0
        
print(array11)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [160]:
#체크무늬 만들기 01010101

array12 = np.ones((8,8))

array12[::2,1::2]=0  #array[[1,3,5,7],:] 이건 인덱싱!!
array12[1::2,::2]=0

print(array12)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [186]:
np.tile( np.eye(2), (4,4) )

#tile 명령은 동일한 배열을 반복하여 연결한다.

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [185]:
#tile 명령은 동일한 배열을 반복하여 연결한다.
np.tile( np.eye(2), (3,2))
# ㄴ 모양으로 만들어짐 ↓3 →2

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [213]:
array13 = np.arange(11)
for i in array13:
    if 3< i <7:
        array13[i] *= (-1)
print(array13)

array13 = np.arange(11)
array13[4:7] *= -1
print(array13)

#강사님 답변
a = np.arange(11)
a[ (3<a) & (a<7) ] *= -1  # 3<a and 7>a 해도 상관없음
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [219]:
a = np.arange(1,100)
array3rd = a[ a%3==0 ]
array3rd.sum()

np.arange(3,101,3).sum()

1683

In [221]:
np.arange(1,10)/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [228]:
np.linspace(0.1,0.9,9)

#linspace(start, stop, num, endpoint, retstep, dtype, axis)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [229]:
print(np.linspace.__doc__)


    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to gen

In [ ]:
#로또번호 사용자가 입력한 수만큼 팔기

import numpy as np

while True:
    try:
        inputNum = int(input())
        allNum = np.arange(1,46)
        for i in range(inputNum):
            newArray = np.random.choice(allNum, 6, replace = False)
            result = np.stack([result, newArray])
        print(result)
        break
    except:
        print('자연수만 입력해주세요.')


 4


자연수만 입력해주세요.


In [2]:
import numpy as np

allNum = np.arange(1,46)

inputNum = int(input())
for i in range(inputNum):
    newArray = np.random.choice(allNum, 6, replace = False)
    result = np.stack([result, newArray])
print(result)

print('')

 5


NameError: name 'result' is not defined

In [1]:
# 강사님 답안

import numpy as np

while True:
    try:
        count = int(input('로또 몇개 드릴까요?'))
        if count <= 0:
            raise Error #음수 거르기
        numbers = np.arange(1,46)
        lottos = [np.sort(np.random.choice(numbers, 6, replace=False))
                  for _ in range(count)]
        display(lottos)
        break
    except:
        print('자연수만 입력해주세요')

로또 몇개 드릴까요? 5


[array([ 7, 11, 12, 25, 31, 36]),
 array([ 5, 18, 24, 35, 36, 40]),
 array([ 1, 10, 12, 16, 22, 31]),
 array([ 4, 26, 29, 32, 37, 39]),
 array([ 1,  5,  8, 22, 23, 45])]

In [18]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])
# 200ms를 넘기는 값의 개수는 몇 개일까용

len(resp_time[ resp_time>200 ])

(resp_time>200).sum() #허무합니다:)

8

In [22]:
print('제1분위수:',np.percentile(resp_time, 25))
print('제2분위수:',np.percentile(resp_time, 50))
print('제3분위수:',np.percentile(resp_time, 75))
print('제4분위수:',np.percentile(resp_time, 100))

제1분위수: 71.5
제2분위수: 131.0
제3분위수: 175.5
제4분위수: 218.0


In [17]:
import numpy as np

while True:
    try:
        num = int(input())
        if num <=0:
            raise Error
        print(np.stack((np.random.choice(np.arange(1,46),6,replace=False)
                        for i in range (num) )))
        break
    except:
        print('자연수만 입력해주세요')

 j


자연수만 입력해주세요


 3


[[ 7  8 29 43 12  6]
 [20 19 23  2  1 13]
 [24 11 44 42 37 35]]


In [18]:
import numpy as np

p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

maxResult = np.bincount(result)

print(f'{ p[maxResult.argmax()] }가 {max(maxResult)}표로 반장으로 선출되었습니다.')

뽀로로가 81표로 반장으로 선출되었습니다.


In [2]:
import numpy as np

np.ones((2, 2, 2, 3), dtype='U4')

array([[[['1', '1', '1'],
         ['1', '1', '1']],

        [['1', '1', '1'],
         ['1', '1', '1']]],


       [[['1', '1', '1'],
         ['1', '1', '1']],

        [['1', '1', '1'],
         ['1', '1', '1']]]], dtype='<U4')